### PR TITLE
Basic responsive layout + minor style upgrades

### PR DESCRIPTION
**Pull request by jhuddle**
Hi Andrew - great project, thanks for doing this!

I saw your call-out on FB for collaboration on the UI side of things, so this PR adds some basic responsivity (mostly for the benefit of mobile users) plus some small style upgrades. I've kept it reasonably faithful to your original style so far, and I've not touched the original `main.css` or element layout at all yet - but I think the HTML could benefit from some semantic restructuring for accessibility purposes and to unlock more creative possibilities with the CSS. Happy to work on this further with you if you're up for it! :)

- Jamie

### CODE REVIEW

**Comment by qwandor** [comment]
Thanks a lot Jamie! I've been busy the last few days with some other things, but this looks pretty good. I'll try to have a proper look soon and get it merged, I just want to tweak a few things first.

**Comment by qwandor** [comment]
I think I'm happy enough with this now to merge it and push it to production, but there are a few issues I'd still like to fix:

* For some reason, putting the table row borders on the `tr` rather than the `td` results in them being an inconsistent width.
* The table layout goes weird at some narrower screen widths. I guess this is to do with the grid layout thing you do, I don't know how that works.
* At some intermediate screen widths it breaks some longer dance style names (e.g. "English ceilidh") across two lines, and makes them wider than they should be.

**Comment by jhuddle** [comment]
Great - I see you moved a few things around after the merge too, did that fix everything or is there still anything you'd like me to look at for a future PR?

**Comment by qwandor** [comment]
I think I've got the grid layout looking better now, but the other two issues are still there. If you have any thoughts they would be welcome.

**Comment by qwandor** [comment]
I've filed #3 and #4 to track the remaining issues from this.

**Pull request merged**
